Repository CSID-DGU/2024-1-CECD1-Tripple-5, pull requests merged in 2024-06, with the labels that each got.

#12 🎉Init: Ai Case1/2 Setting
  2024_서희찬.md
  README.md
  ai/case1/.keep
  ai/case2/.keep
Labels: documentation

#17 :sparkles: Feat: 숙소/식당/관광명소 구분 리트리버 구축
  ai/case2/__pycache__/utils.cpython-311.pyc
  ai/case2/app.py
  ai/case2/files/숙소.txt
  ai/case2/files/식당.txt
  ai/case2/utils.py
Labels: 🫠 희찬, ✨ Feature

#18 Feat: 서버 구축
  server/.gitignore
  server/README.md
  server/alembic.ini
  server/alembic/README
  server/alembic/env.py
  server/alembic/script.py.mako
  server/app/__init__.py
  server/app/crud.py
  server/app/database.py
  server/app/main.py
  server/app/models.py
  server/app/routers/chat.py
  server/app/schemas.py
  server/app/service/chatbot/chat.py
  server/requirements.txt
Labels: 🐸 세훈, ✨ Feature

#22 :sparkles: Feat: langcahin 연동
  server/app/service/chatbot/chat.py
  server/app/service/chatbot/files/keyword.txt
  server/app/service/chatbot/files/관광명소.txt
  server/app/service/chatbot/files/숙소.txt
  server/app/service/chatbot/files/식당.txt
  server/app/service/chatbot/prompts.py
  server/app/service/chatbot/utils2.py
  server/app/service/others/.keep
Labels: 🫠 희찬, ✨ Feature

#23 :sparkles: Feat: 출력 json형태
  server/app/main.py
  server/app/service/chatbot/chat.py
  server/app/service/chatbot/prompts.py
  server/app/service/chatbot/utils2.py
Labels: 🫠 희찬, ✨ Feature
